replicaCount: 1

green:
  enabled: false

blue:
  enabled: false

productionSlot: blue

hpa:
  enabled: true
  maxReplicas: 2
  # average total CPU usage per pod (1-100)
  cpu: 80
  # average memory usage per pod (100Mi-1Gi)
  memory:
  # average http requests per second per pod (k8s-prometheus-adapter)
  requests:


imageBlue:
  repository: 818353068367.dkr.ecr.eu-central-1.amazonaws.com/tony
  tag:
  pullPolicy: IfNotPresent

imageGreen:
  repository: 818353068367.dkr.ecr.eu-central-1.amazonaws.com/tony
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: go-app.stark-net.com
      paths:
        - path: "/"
          backendsuffix: "-blue"
    - host: go-app-demo.stark-net.com
      paths:
        - path: "/"
          backendsuffix: "-green"

  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
